### ISSUE TITLE
can not add repository.

### ISSUE THREAD

**Issue by hedmo** [kakra/nvidia-vulkan#1]
hi i am trying to add this repository but it does not work.when i type :`eselect repository add nvidia-vulkan git https://github.com/kakra/nvidia-vulkan.git`

i get : `mya51 /home/hedmo # eselect repository add nvidia-vulkan git https://github.com/kakra/nvidia-vulkan.git
--2019-11-21 17:36:49--  https://qa-reports.gentoo.org/output/repos/repositories.xml
Resolving qa-reports.gentoo.org... 140.211.166.190, 2001:470:ea4a:1:230:48ff:fef8:9fdc
Connecting to qa-reports.gentoo.org|140.211.166.190|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 284371 (278K) [application/xml]
Saving to: '/root/.cache/eselect-repo/repositories.xml'

repositories.xml                        100%[==============================================================================>] 277.71K   360KB/s    in 0.8s    

2019-11-21 17:36:51 (360 KB/s) - '/root/.cache/eselect-repo/repositories.xml' saved [284371/284371]

Adding nvidia-vulkan to /etc/portage/repos.conf/eselect-repo.conf ...
Repository nvidia-vulkan added
mya51 /home/hedmo # emerge -av nvidia-drivers::nvidia-vulkan
!!! Section 'nvidia-vulkan' in repos.conf has location attribute set to nonexistent directory: '/var/db/repos/nvidia-vulkan'
WARNING: One or more repositories have missing repo_name entries:

	/var/db/repos/nvidia-vulkan/profiles/repo_name

NOTE: Each repo_name entry should be a plain text file containing a
unique name for the repository on the first line.

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "x11-drivers/nvidia-drivers::nvidia-vulkan".
mya51 /home/hedmo # `

regards hedmo

**Comment by kakra** [comment]
It seems obvious that you ran as root, but did you run as root?

Also, the missing `repo_name` indicates that you didn't sync. Please run `emaint sync -a` to sync all repositories.

**Comment by hedmo** [comment]
@kakra 

thank. it worked after `emaint sync -a`.i had made my sync for that day and did not want to sync again.
`Please note: common gentoo-netiquette says you should not sync more
than once a day.  Users who abuse the rsync.gentoo.org rotation
may be added to a temporary ban list.`

"suggestion"

To use this overlay.

see: [https://wiki.gentoo.org/wiki/Eselect/Repository](url)
 run:

`eselect repository add nvidia-vulkan git https://github.com/kakra/nvidia-vulkan.git`

and sync to the new repository:

`emaint sync --repo nvidia-vulkan`

Then unmask/mask as appropriate.

These drivers are checked with the Vulkan GPUinfo diagnostic software. You can see my submitted entries here:

https://vulkan.gpuinfo.org/listreports.php?submitter=hurikhan77

**Comment by kakra** [comment]
I've already prepared a branch which matches your suggestion. Are you ok with that?

**Comment by hedmo** [comment]
@kakra i am ok with that .thanks for this repo.

best regards Hedmo
