### ISSUE TITLE
ERROR: Kernel configuration is invalid

### ISSUE THREAD

**Issue by hedmo** [kakra/nvidia-vulkan#2]
hi again .

the x11-drivers/nvidia-drivers-435.27-r107 does not build against the new sys-kernel/gentoo-sources-5.4.0.

`test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)`

regards hedmo

**Comment by kakra** [comment]
This is probably expected as kernel devs are in the process of removing APIs used by the driver. This will need a new major update from NVIDIA (so we'd need a rebase of the vulkan driver to a 5.4 compatible driver). You can raise your voice in the NVIDIA thread of the DXVK project as it has NVIDIA employees involved. Usually, a rebase should come within a few weeks. It may take longer this time.

I recommend sticking with 5.3.x for a while. I'll add support for 5.4 when either NVIDIA rebased or when patches show up that restore compatibility.

If you figure out that a new major release builds with kernel 5.4 (aka v440 or above, I didn't check, it may be out already), then it'd be time to kindly ask in the aforementioned thread for a rebase.

Until then, I'll close this thread. Feel free to reopen with new info on updates.

PS: Didn't close, I tagged it instead.

**Comment by hedmo** [comment]
@kakra 

thank for the reply.i am running `x11-drivers/nvidia-drivers-440.36:0/440::gentoo` with 5.4.i did check if there where any patches for building against the 5.4 kernel but none..rolling back to 5.3 and raising my voice at DXVK.by the way x11-drivers/nvidia-drivers-435.27-r108 is out..

regards hedmo

**Comment by kakra** [comment]
If 440.36 is working, we should ask NVIDIA for a rebase of 435.27 to the current beta driver. Until then, I've rolled out 435.27.08 in this repository.

**Comment by hedmo** [comment]
@kakra if you want you can update to nvidia-drivers-440.43-r101 . its working with kernel-5.4.3 but the wayland useflag will fail.

regards hedmo

**Comment by kakra** [comment]
Yes, you cannot just rename the ebuild, you have to base it off the direct predecessor ebuild. In this case, the wayland sover seems to have changed. I'm in the process of creating a new ebuild. I do not use wayland so I'd be happy if you could test it then. If it won't work then, please open a new issue about that so we can close this one. Wayland support is off-topic in this report.
